/*--+----1----+----2----+----3----+----4----+----5----+----6----+----7----+--*/
/*  System Name   : INSECT POKEMON                                           */
/*  Machine & OS  : Sony PlayStation / PlayStation OS ( R3000 )              */
/*  Language      : GNU C                                                    */
/*                                                                           */
/*  File Contents : SPRITE OFFSET                                            */
/*  File Attribute: HEADER                                                   */
/*  File Name     : ANMDATA.H                                                */
/*                                                                           */
/*--+----1----+----2----+----3----+----4----+----5----+----6----+----7----+--*/
#ifndef _ANMDATA_H_
#define _ANMDATA_H_

/*--+----1----+----2----+----3----+----4----+----5----+----6----+----7----+--*/
/*  SPRITE OFFSET                                                            */
/*--+----1----+----2----+----3----+----4----+----5----+----6----+----7----+--*/
#define roll_ofs		(0)

extern CzAnimData *St_SequenceTbl[];

#endif  /* _ANMDATA_H_ */
