/*--+----1----+----2----+----3----+----4----+----5----+----6----+----7----+--*/
/*  System Name   : INSECT POKEMON                                           */
/*  Machine & OS  : Sony PlayStation / PlayStation OS ( R3000 )              */
/*  Language      : GNU C                                                    */
/*                                                                           */
/*  File Contents : SPRITE OFFSET                                            */
/*  File Attribute: HEADER                                                   */
/*  File Name     : ANMDATA.H                                                */
/*                                                                           */
/*--+----1----+----2----+----3----+----4----+----5----+----6----+----7----+--*/
#ifndef _ANMDATA_H_
#define _ANMDATA_H_

/*--+----1----+----2----+----3----+----4----+----5----+----6----+----7----+--*/
/*  SPRITE OFFSET                                                            */
/*--+----1----+----2----+----3----+----4----+----5----+----6----+----7----+--*/
#define fixmenu_ofs		(0)
#define fixmenu2_ofs	(fixmenu_ofs + 5)
#define fixb2b_ofs		(fixmenu2_ofs + 7)
#define fix2_ofs		(fixb2b_ofs + 1)
#define fix_ofs			(fix2_ofs + 11)

#endif  /* _ANMDATA_H_ */
