/*--+----1----+----2----+----3----+----4----+----5----+----6----+----7----+--*/
/*  System Name   : INSECT POKEMON                                           */
/*  Machine & OS  : Sony PlayStation / PlayStation OS ( R3000 )              */
/*  Language      : GNU C                                                    */
/*                                                                           */
/*  File Contents : SPRITE OFFSET                                            */
/*  File Attribute: HEADER                                                   */
/*  File Name     : ANMDATA.H                                                */
/*                                                                           */
/*--+----1----+----2----+----3----+----4----+----5----+----6----+----7----+--*/
#ifndef _ANMDATA_H_
#define _ANMDATA_H_

/*--+----1----+----2----+----3----+----4----+----5----+----6----+----7----+--*/
/*  SPRITE OFFSET                                                            */
/*--+----1----+----2----+----3----+----4----+----5----+----6----+----7----+--*/
#define fix_ofs		(0)
#define efe1_ofs	(fix_ofs + 59)
#define gol_ofs		(efe1_ofs + 9)
#define renda_ofs	(gol_ofs + 1)
#define ap2_ofs		(renda_ofs + 5)
#define vs_ofs		(ap2_ofs + 10)
#define nizi_ofs	(vs_ofs + 2)
#define name_ofs	(nizi_ofs + 1)
#define namevs_ofs	(name_ofs + 2)
#define syouri_ofs	(namevs_ofs + 2)
#define flare_ofs	(syouri_ofs + 1)
#define beem3_ofs	(flare_ofs + 8)
#define logo_ofs	(beem3_ofs + 4)

#endif  /* _ANMDATA_H_ */
